version: '3.0'

services:
  config:
    build: config
    ports:
      - "9001:9001"
  service-registry:
    build: service-registry
    ports:
      - "8701:8701"
      - "8705:8705"

  user-service:
    build: user-service
    expose:
      - "8021"

  blog-service:
    build: blog-service
    ports:
      - "8031:8031"
  auth-service:
    build: auth-service
    ports:
      - "8051:8051"

  dashboard:
    build: dashboard
    ports:
      - "8040:8040"

  gateway:
    build: gateway
    ports:
      - "8080:8010"

  mysql-db-blog-user:
    build: mysql-user-db
    ports:
      - "3206:3306"

  mysql-db-blog-blog:
    build: mysql-blog-db
    ports:
      - "3106:3306"
