server:
  port: 8021

spring:
  datasource:
    url: jdbc:mysql://mysql-db-blog-user:3306/blog_user
    driver-class-name: com.mysql.jdbc.Driver
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_USER_PWD}






