server:
  context-path: /uaa
  port: 8051

spring:
  datasource:
    url: jdbc:mysql://mysql-db-blog-user:3306/blog_user
    driver-class-name: com.mysql.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  redis:
    host: redis-server
    port: 6379
    pool:
      max-active: 8

security:
  oauth2:
    resource:
      filter-order: 3