server:
  context-path: /user
  port: 8021

spring:
  datasource:
    url: jdbc:mysql://mysql-db-blog-user:3306/blog_user
    driver-class-name: com.mysql.jdbc.Driver
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_USER_PWD}

security:
  oauth2:
    client:
      client-id: user-service
      client-secret: user-service
      access-token-uri: http://auth-service:8051/uaa/oauth/token
      grant-type: client_credentials
      scope:
        - server